AWSTemplateFormatVersion: "2010-09-09"

Description: (SO0050-search-engine) Media2Cloud - create elasticsearch cluster for search feature

Mappings:
    Elasticsearch:
        Domain:
            Version: 7.9
        EBSOptions:
            VolumeType: gp2
        Index:
            Name: media-analysis

Parameters:
    SolutionId:
        Type: String
        Description: "part of the resource naming"
    SolutionUuid:
        Type: String
        Description: "unique solution uuid"
    Version:
        Type: String
        Description: "solution version"
    AnonymousUsage:
        Type: String
        Description: "anonymous usage"
    RootStackName:
        Type: String
        Description: "part of the resource naming"
    S3Bucket:
        Type: String
        Description: solution bucket
        AllowedPattern: "[a-z][a-z0-9-_]*"
    KeyPrefix:
        Type: String
        Description: solution key prefix
    CustomResourceArn:
        Type: String
        Description: for post-processing
    ElasticsearchCluster:
        Type: String
        Description: "configure Amazon Elasticsearch cluster"
        AllowedValues:
            - Development and Testing (t3.small=0,m5.large=1,volume=10,az=1)
            - Suitable for Production Workload (t3.small=3,m5.large=2,volume=20,az=2)
            - Recommended for Production Workload (t3.small=3,m5.large=4,volume=20,az=2)
            - Recommended for Large Production Workload (t3.small=3,m5.large=6,volume=40,az=3)
        Default: Development and Testing (t3.small=0,m5.large=1,volume=10,az=1)

Metadata:
    AWS::CloudFormation::Interface:
        ParameterGroups:
            -
                Label:
                    default: "Solution Configuration"
                Parameters:
                    - SolutionId
                    - RootStackName
                    - S3Bucket
                    - KeyPrefix
                    - SolutionUuid
                    - Version
                    - AnonymousUsage
            -
                Label:
                    default: "Elasticsearch Configuration"
                Parameters:
                    - ElasticsearchCluster
            -
                Label:
                    default: "Other resources"
                Parameters:
                    - CustomResourceArn
        ParameterLabels:
            SolutionId:
                default: "Solution Id"
            RootStackName:
                default: "Top Stack Name"
            S3Bucket:
                default: "Solution Bucket"
            KeyPrefix:
                default: "Solution KeyPrefix"
            CustomResourceArn:
                default: "Custom Resource Arn"
            ElasticsearchCluster:
                default: "Elasticsearch cluster"
            SolutionUuid:
                default: "Solution Uuid"
            Version:
                default: "Solution Version"
            AnonymousUsage:
                default: "Anonymous Usage"

Conditions:
    bDedicatedNodes: !Not [
        !Equals [
            "0",
            !Select [1,
                !Split ["=",
                    !Select [0,
                        !Split [",",
                            !Select [0,
                                !Split [")",
                                    !Select [1,
                                        !Split ["(",
                                            !Ref ElasticsearchCluster
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
    bSingleAZ: !Equals [
        "1",
        !Select [1,
            !Split ["=",
                !Select [3,
                    !Split [",",
                        !Select [0,
                            !Split [")",
                                !Select [1,
                                    !Split ["(",
                                        !Ref ElasticsearchCluster
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
    bTwoAZs: !Equals [
        "2",
        !Select [1,
            !Split ["=",
                !Select [3,
                    !Split [",",
                        !Select [0,
                            !Split [")",
                                !Select [1,
                                    !Split ["(",
                                        !Ref ElasticsearchCluster
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
    bThreeAZs: !Equals [
        "3",
        !Select [1,
            !Split ["=",
                !Select [3,
                    !Split [",",
                        !Select [0,
                            !Split [")",
                                !Select [1,
                                    !Split ["(",
                                        !Ref ElasticsearchCluster
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]

Resources:
    LowerCaseDomainName:
        Type: Custom::StringManipulation
        Properties:
            ServiceToken: !Ref CustomResourceArn
            Data:
                InputString: !Sub "${SolutionId}-${RootStackName}-storage"
                Operations: "lower,maxlen=28,minlen=3,dash"
                OutputReference: ElasticsearchDomainName

    Elasticsearch:
        Type: AWS::Elasticsearch::Domain
        Metadata:
            cfn_nag:
                rules_to_suppress:
                    -
                        id: W28
                        reason: "Elasticsearch engine is explicitly assigned with predefined name"
        Properties:
            AccessPolicies:
                Version: "2012-10-17"
                Statement:
                    -
                        Effect: Allow
                        Principal:
                            AWS: !Sub "${AWS::AccountId}"
                        Action:
                            - es:ESHttpDelete
                            - es:ESHttpGet
                            - es:ESHttpHead
                            - es:ESHttpPost
                            - es:ESHttpPut
                        Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${LowerCaseDomainName.OutputString}/*"
            AdvancedOptions:
                rest.action.multi.allow_explicit_index: "true"
            DomainEndpointOptions:
                EnforceHTTPS: true
                TLSSecurityPolicy: Policy-Min-TLS-1-2-2019-07
            DomainName: !GetAtt LowerCaseDomainName.OutputString
            EBSOptions:
                EBSEnabled: true
                Iops: 0
                VolumeSize: !Select [1,
                    !Split ["=",
                        !Select [2,
                            !Split [",",
                                !Select [0,
                                    !Split [")",
                                        !Select [1,
                                            !Split ["(",
                                                !Ref ElasticsearchCluster
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
                VolumeType: !FindInMap [
                    "Elasticsearch",
                    "EBSOptions",
                    "VolumeType"
                ]
            ElasticsearchClusterConfig:
                DedicatedMasterEnabled: !If [
                    bDedicatedNodes,
                    true,
                    false
                ]
                DedicatedMasterCount: !If [
                    bDedicatedNodes,
                    !Select [1,
                        !Split ["=",
                            !Select [0,
                                !Split [",",
                                    !Select [0,
                                        !Split [")",
                                            !Select [1,
                                                !Split ["(",
                                                    !Ref ElasticsearchCluster
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ],
                    !Ref "AWS::NoValue"
                ]
                DedicatedMasterType: !If [
                    bDedicatedNodes,
                    !Sub [
                        "${x0}.elasticsearch", {
                            x0: !Select [0,
                                !Split ["=",
                                    !Select [0,
                                        !Split [",",
                                            !Select [0,
                                                !Split [")",
                                                    !Select [1,
                                                        !Split ["(",
                                                            !Ref ElasticsearchCluster
                                                        ]
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        }
                    ],
                    !Ref "AWS::NoValue"
                ]
                InstanceCount: !Select [1,
                    !Split ["=",
                        !Select [1,
                            !Split [",",
                                !Select [0,
                                    !Split [")",
                                        !Select [1,
                                            !Split ["(",
                                                !Ref ElasticsearchCluster
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    ]
                ]
                InstanceType: !Sub [
                    "${x0}.elasticsearch", {
                        x0: !Select [0,
                            !Split ["=",
                                !Select [1,
                                    !Split [",",
                                        !Select [0,
                                            !Split [")",
                                                !Select [1,
                                                    !Split ["(",
                                                        !Ref ElasticsearchCluster
                                                    ]
                                                ]
                                            ]
                                        ]
                                    ]
                                ]
                            ]
                        ]
                    }
                ]
                ZoneAwarenessEnabled: !If [
                    bSingleAZ,
                    false,
                    true
                ]
                ZoneAwarenessConfig: !If [
                    bSingleAZ,
                    !Ref "AWS::NoValue",
                    AvailabilityZoneCount: !If [
                        bThreeAZs,
                        3,
                        2
                    ]
                ]
            ElasticsearchVersion: !FindInMap [
                "Elasticsearch",
                "Domain",
                "Version"
            ]
            EncryptionAtRestOptions:
                Enabled: true
            NodeToNodeEncryptionOptions:
                Enabled: true
            Tags:
                -
                    Key: SolutionId
                    Value: !Ref SolutionId

    CreateIndex:
        Type: Custom::CreateIndex
        Properties:
            ServiceToken: !Ref CustomResourceArn
            Data:
                DomainEndpoint: !GetAtt Elasticsearch.DomainEndpoint
                IndexName: !FindInMap [
                    "Elasticsearch",
                    "Index",
                    "Name"
                ]

    SendConfig:
        DependsOn: CreateIndex
        Type: Custom::SendConfig
        Properties:
            ServiceToken: !Ref CustomResourceArn
            Data:
                SolutionId: !Ref SolutionId
                SolutionUuid: !Ref SolutionUuid
                Version: !Ref Version
                AnonymousUsage: !Ref AnonymousUsage
                ElasticsearchCluster: !Ref ElasticsearchCluster

Outputs:
    DomainName:
        Value: !Ref Elasticsearch
        Description: "Elasticsearch Domain Name"
    DomainEndpoint:
        Value: !GetAtt Elasticsearch.DomainEndpoint
        Description: "Elasticsearch Domain Endpoint"
    IndexName:
        Value: !FindInMap [
            "Elasticsearch",
            "Index",
            "Name"
        ]
        Description: "Elasticsearch Index Name"
    Version:
        Value: !FindInMap [
            "Elasticsearch",
            "Domain",
            "Version"
        ]
        Description: "Elasticsearch Version"
